-- Attendence Table --
CREATE TABLE `attendence` (
  `CLASS_ID` varchar(10) NOT NULL,
  `CLASS_NAME` varchar(15) NOT NULL,
  `STUDENT_ATTENDED` int NOT NULL,
  `TAKEN_BY` varchar(40) NOT NULL,
  PRIMARY KEY (`CLASS_ID`),
  KEY `CLASS_NAME_HON_idx` (`CLASS_NAME`),
  KEY `STUDENT_ATTENDED_idx` (`STUDENT_ATTENDED`),
  KEY `TAKEN_BY_ATTND_idx` (`TAKEN_BY`),
  CONSTRAINT `CLASS_ID` FOREIGN KEY (`CLASS_ID`) REFERENCES `hons_class` (`CLASS_ID`),
  CONSTRAINT `CLASS_ID1` FOREIGN KEY (`CLASS_ID`) REFERENCES `gen_class` (`CLASS_ID`),
  CONSTRAINT `CLASS_NAME_GEN` FOREIGN KEY (`CLASS_NAME`) REFERENCES `gen_paper` (`PAPER_ID`),
  CONSTRAINT `CLASS_NAME_HON` FOREIGN KEY (`CLASS_NAME`) REFERENCES `hons_paper` (`PAPER_ID`),
  CONSTRAINT `STUDENT_ATTENDED` FOREIGN KEY (`STUDENT_ATTENDED`) REFERENCES `student` (`STUDENT_ROLL`),
  CONSTRAINT `TAKEN_BY_ATTND` FOREIGN KEY (`TAKEN_BY`) REFERENCES `teacher` (`TEACHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- Department Table -- 
CREATE TABLE `department` (
  `DEPT_ID` varchar(8) NOT NULL,
  `DEPT_NAME` varchar(40) NOT NULL,
  `NO_OF_COURSE_OFFERD` int NOT NULL,
  PRIMARY KEY (`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


-- Enroll Table -- 
CREATE TABLE `enroll` (
  `ENROLL_ID` varchar(12) NOT NULL,
  `STUDENT_ROLL` int NOT NULL,
  `COURSE_ID` varchar(40) NOT NULL,
  `STUDENT_YEAR` varchar(10) NOT NULL,
  `GENERAL_PAPER_TAKEN` varchar(15) NOT NULL,
  PRIMARY KEY (`ENROLL_ID`),
  KEY `STUDENT_ROLL_idx` (`STUDENT_ROLL`),
  KEY `GENERAL_PAPER_TAKEN_idx` (`GENERAL_PAPER_TAKEN`),
  CONSTRAINT `GENERAL_PAPER_TAKEN` FOREIGN KEY (`GENERAL_PAPER_TAKEN`) REFERENCES `gen_paper` (`PAPER_ID`),
  CONSTRAINT `STUDENT_ROLL` FOREIGN KEY (`STUDENT_ROLL`) REFERENCES `student` (`STUDENT_ROLL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- Genral Class Table -- 
CREATE TABLE `gen_class` (
  `CLASS_ID` varchar(10) NOT NULL,
  `CLASS_NAME` varchar(50) NOT NULL,
  `TAKEN_BY` varchar(40) NOT NULL,
  `CLASS_STUDENTS` int NOT NULL,
  PRIMARY KEY (`CLASS_ID`),
  KEY `CLASS_NAME1_idx` (`CLASS_NAME`),
  KEY `TAKEN_BY1_idx` (`TAKEN_BY`),
  KEY `CLASS_STUDENTS1_idx` (`CLASS_STUDENTS`),
  CONSTRAINT `CLASS_NAME1` FOREIGN KEY (`CLASS_NAME`) REFERENCES `gen_paper` (`PAPER_ID`),
  CONSTRAINT `CLASS_STUDENTS1` FOREIGN KEY (`CLASS_STUDENTS`) REFERENCES `student` (`STUDENT_ROLL`),
  CONSTRAINT `TAKEN_BY1` FOREIGN KEY (`TAKEN_BY`) REFERENCES `teacher` (`TEACHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- General Paper Table --
CREATE TABLE `gen_paper` (
  `PAPER_ID` varchar(15) NOT NULL,
  `PAPER_NAME` varchar(50) NOT NULL,
  `PAPER_DEPT` varchar(25) NOT NULL,
  `PAPER_SEM` varchar(12) NOT NULL,
  `PAPER_TAKEN_BY` varchar(40) NOT NULL,
  PRIMARY KEY (`PAPER_ID`),
  KEY `PAPER_TAKEN_BY_idx` (`PAPER_TAKEN_BY`),
  CONSTRAINT `PAPER_TAKEN_BY2` FOREIGN KEY (`PAPER_TAKEN_BY`) REFERENCES `teacher` (`TEACHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- Hons. Class Table--
CREATE TABLE `hons_class` (
  `CLASS_ID` varchar(10) NOT NULL,
  `CLASS_NAME` varchar(50) NOT NULL,
  `TAKEN_BY` varchar(40) NOT NULL,
  `CLASS_STUDENTS` int NOT NULL,
  PRIMARY KEY (`CLASS_ID`),
  KEY `TAKEN_BY_idx` (`TAKEN_BY`),
  KEY `CLASS_STUDENTS_idx` (`CLASS_STUDENTS`),
  KEY `CLASS_NAME_idx` (`CLASS_NAME`),
  CONSTRAINT `CLASS_NAME` FOREIGN KEY (`CLASS_NAME`) REFERENCES `hons_paper` (`PAPER_ID`),
  CONSTRAINT `CLASS_STUDENTS` FOREIGN KEY (`CLASS_STUDENTS`) REFERENCES `student` (`STUDENT_ROLL`),
  CONSTRAINT `TAKEN_BY` FOREIGN KEY (`TAKEN_BY`) REFERENCES `teacher` (`TEACHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- Hons. Paper -- 
CREATE TABLE `hons_paper` (
  `PAPER_ID` varchar(15) NOT NULL,
  `PAPER_NAME` varchar(50) NOT NULL,
  `PAPER_DEPT` varchar(25) NOT NULL,
  `PAPER_COURSE_ID` varchar(15) NOT NULL,
  `PAPER_SEM` varchar(12) NOT NULL,
  `PAPER_TAKEN_BY` varchar(40) NOT NULL,
  PRIMARY KEY (`PAPER_ID`),
  KEY `PAPER_TAKEN_BY_idx` (`PAPER_TAKEN_BY`),
  CONSTRAINT `PAPER_TAKEN_BY` FOREIGN KEY (`PAPER_TAKEN_BY`) REFERENCES `teacher` (`TEACHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- PG course --
CREATE TABLE `pg_course` (
  `COURSE_ID` varchar(40) NOT NULL,
  `COURSE_DEPT` varchar(8) NOT NULL,
  `COURSE_NAME` varchar(60) NOT NULL,
  PRIMARY KEY (`COURSE_ID`),
  KEY `COURSE_DEPT_idx` (`COURSE_DEPT`),
  CONSTRAINT `PG_COURSE_DEPT` FOREIGN KEY (`COURSE_DEPT`) REFERENCES `department` (`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--Student table --
CREATE TABLE `student` (
  `STUDENT_ROLL` int NOT NULL,
  `STUDENT_NAME` varchar(50) DEFAULT NULL,
  `STUDENT_DEPT` varchar(8) NOT NULL,
  `STUDENT_YEAR` varchar(10) DEFAULT NULL,
  `STUDENT_SEM` int NOT NULL,
  PRIMARY KEY (`STUDENT_ROLL`),
  KEY `STU_DEPT_idx` (`STUDENT_DEPT`),
  CONSTRAINT `STU_DEPT` FOREIGN KEY (`STUDENT_DEPT`) REFERENCES `department` (`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- Teacher Table --
CREATE TABLE `teacher` (
  `TEACHER_DEPT` varchar(8) NOT NULL,
  `TEACHER_ID` varchar(40) NOT NULL,
  `TEACHER_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`TEACHER_ID`),
  KEY `TEA_DEPT_idx` (`TEACHER_DEPT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- Teacher Credentials --
CREATE TABLE `teacher_credentials` (
  `TEACHER_ID` varchar(40) NOT NULL,
  `PASSWORD` varchar(25) NOT NULL,
  `SCHEDULE_ID` varchar(10) NOT NULL,
  PRIMARY KEY (`TEACHER_ID`),
  KEY `SCHEDULE_idx` (`SCHEDULE_ID`),
  CONSTRAINT `SCHEDULE` FOREIGN KEY (`SCHEDULE_ID`) REFERENCES `teacher_schedules` (`SCHEDULE_ID`),
  CONSTRAINT `TEACHER_ID` FOREIGN KEY (`TEACHER_ID`) REFERENCES `teacher` (`TEACHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- Teacher_schedules --
CREATE TABLE `teacher_schedules` (
  `SCHEDULE_ID` varchar(10) NOT NULL,
  `DAY` varchar(12) NOT NULL,
  `10.00-11.00` varchar(10) NOT NULL,
  `11.00-12.00` varchar(10) NOT NULL,
  `12.00-1.00` varchar(10) NOT NULL,
  `1.30-2.30` varchar(10) NOT NULL,
  `2.30-3.30` varchar(10) NOT NULL,
  `3.30-4.30` varchar(10) NOT NULL,
  `5.30-6.30` varchar(10) DEFAULT NULL,
  `6.30-7.30` varchar(10) DEFAULT NULL,
  `7.30-8.30` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`SCHEDULE_ID`),
  KEY `10.00-11.00_idx` (`10.00-11.00`),
  KEY `11.00-12.00_idx` (`11.00-12.00`),
  KEY `12.00-1.00_idx` (`12.00-1.00`),
  KEY `1.30-2.30_idx` (`1.30-2.30`),
  KEY `2.30-3.30_idx` (`2.30-3.30`),
  KEY `3.30-4.30_idx` (`3.30-4.30`),
  CONSTRAINT `1.30-2.30` FOREIGN KEY (`1.30-2.30`) REFERENCES `hons_class` (`CLASS_ID`),
  CONSTRAINT `1.30-2.30A` FOREIGN KEY (`1.30-2.30`) REFERENCES `gen_class` (`CLASS_ID`),
  CONSTRAINT `10.00-11.00` FOREIGN KEY (`10.00-11.00`) REFERENCES `hons_class` (`CLASS_ID`),
  CONSTRAINT `10.00-11.00A` FOREIGN KEY (`10.00-11.00`) REFERENCES `gen_class` (`CLASS_ID`),
  CONSTRAINT `11.00-12.00` FOREIGN KEY (`11.00-12.00`) REFERENCES `hons_class` (`CLASS_ID`),
  CONSTRAINT `11.00-12.00A` FOREIGN KEY (`11.00-12.00`) REFERENCES `gen_class` (`CLASS_ID`),
  CONSTRAINT `12.00-1.00` FOREIGN KEY (`12.00-1.00`) REFERENCES `hons_class` (`CLASS_ID`),
  CONSTRAINT `12.00-1.00A` FOREIGN KEY (`12.00-1.00`) REFERENCES `gen_class` (`CLASS_ID`),
  CONSTRAINT `2.30-3.30` FOREIGN KEY (`2.30-3.30`) REFERENCES `hons_class` (`CLASS_ID`),
  CONSTRAINT `2.30-3.30A` FOREIGN KEY (`2.30-3.30`) REFERENCES `gen_class` (`CLASS_ID`),
  CONSTRAINT `3.30-4.30` FOREIGN KEY (`3.30-4.30`) REFERENCES `hons_class` (`CLASS_ID`),
  CONSTRAINT `3.30-4.30A` FOREIGN KEY (`3.30-4.30`) REFERENCES `gen_class` (`CLASS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-- UG_course --
CREATE TABLE `ug_course` (
  `COURSE_ID` varchar(40) NOT NULL,
  `COURSE_DEPT` varchar(8) NOT NULL,
  `COURSE_NAME` varchar(60) NOT NULL,
  PRIMARY KEY (`COURSE_ID`),
  KEY `COURSE_DEPT_idx` (`COURSE_DEPT`),
  CONSTRAINT `COURSE_DEPT` FOREIGN KEY (`COURSE_DEPT`) REFERENCES `department` (`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
